## This program creates Neighborhood Delination across different time period

In [15]:
import pandas as pd
import geopandas as gpd
from Qualitative_Analysis_Mapper import Clustering_viz

In [16]:
input_attributes = pd.read_csv("attributes/Cateogrical_data_tract_time.csv")
input_attributes

          tractID  1980  1990  2000  2010
0     17031010100     2     3     0     2
1     17031010201     2     2     2     2
2     17031010202     2     2     2     2
3     17031010300     2     2     2     2
4     17031010400     5     5     2     5
...           ...   ...   ...   ...   ...
1225  17031843500     3     3     3     4
1226  17031843600     0     0     0     0
1227  17031843700     2     2     2     5
1228  17031843800     0     0     0     0
1229  17031843900     0     0     0     4

[1230 rows x 5 columns]

In [17]:
shapefile = gpd.read_file('shp/Cook_County_Tract.shp')
shapefile = shapefile.rename(columns={'GEOID10': 'tractID'})
shapefile

          tractID                                           geometry
0     17031010300  POLYGON ((-87.67133 42.01937, -87.67121 42.019...
1     17031010400  POLYGON ((-87.66345 42.01283, -87.66321 42.012...
2     17031010600  POLYGON ((-87.67059 42.00537, -87.67046 42.005...
3     17031020100  POLYGON ((-87.69024 42.01265, -87.69024 42.012...
4     17031280800  POLYGON ((-87.69151 41.88111, -87.69147 41.881...
...           ...                                                ...
1313  17031823901  POLYGON ((-87.85680 41.67987, -87.85676 41.680...
1314  17031826800  POLYGON ((-87.67975 41.64819, -87.67910 41.648...
1315  17031710300  POLYGON ((-87.66361 41.75768, -87.66330 41.757...
1316  17031828506  POLYGON ((-87.55864 41.54282, -87.55850 41.542...
1317  17031825600  POLYGON ((-87.72777 41.58756, -87.72765 41.587...

[1318 rows x 2 columns]

In [18]:
param = {
    'title': "Neighborhood, Cook County (tract level)",
    'subject': "NEIGHBORHOOD",
    'filename_suffix': "Cook_2018_from_ACS_tract_from_file", 
    'layers': [1980,1990,2000, 2010],
    'inputCSV': input_attributes,   
    'shapefile': shapefile, 
    'Stacked_Chart': True,               #Visualize Temporal Change over periods
    'Parallel_Categories_Diagram': True, #Quantifies Changes over multiple periods
    'Chord_Diagram': True                #Quantifies Change between two periods
}
Clustering_viz(param)

To see your visualization, Click the URL below (or locate files):
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ\QUAL_Cook_2018_from_ACS_tract_from_file\index.html
Advanced options are available in
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ/QUAL_Cook_2018_from_ACS_tract_from_file/data/CONFIG_Cook_2018_from_ACS_tract_from_file.js

In [19]:
param = {
    'title': "Neighborhood, Cook County (tract level)",
    'subject': "NEIGHBORHOOD",
    'filename_suffix': "Temporal_Parallel_Categories_Diagram", 
    'layers': [1980,1990,2000, 2010],
    'inputCSV': input_attributes,   
    'shapefile': shapefile, 
    'Stacked_Chart': False,               #Visualize Temporal Change over periods
    'Parallel_Categories_Diagram': True, #Quantifies Changes over multiple periods
    'Chord_Diagram': False                #Quantifies Change between two periods
}
Clustering_viz(param)

To see your visualization, Click the URL below (or locate files):
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ\QUAL_Temporal_Parallel_Categories_Diagram\index.html
Advanced options are available in
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ/QUAL_Temporal_Parallel_Categories_Diagram/data/CONFIG_Temporal_Parallel_Categories_Diagram.js

In [20]:
param = {
    'title': "Neighborhood, Cook County (tract level)",
    'subject': "NEIGHBORHOOD",
    'filename_suffix': "Temporal_Chord_Diagram", 
    'layers': [1980,1990,2000, 2010],
    'inputCSV': input_attributes,   
    'shapefile': shapefile, 
    'Stacked_Chart': False,               #Visualize Temporal Change over periods
    'Parallel_Categories_Diagram': False, #Quantifies Changes over multiple periods
    'Chord_Diagram': True                #Quantifies Change between two periods
}
Clustering_viz(param)

To see your visualization, Click the URL below (or locate files):
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ\QUAL_Temporal_Chord_Diagram\index.html
Advanced options are available in
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ/QUAL_Temporal_Chord_Diagram/data/CONFIG_Temporal_Chord_Diagram.js

In [21]:
param = {
    'title': "Neighborhood, Cook County (tract level)",
    'subject': "NEIGHBORHOOD",
    'filename_suffix': "Stacked_Chart", 
    'layers': [1980,1990,2000, 2010],
    'inputCSV': input_attributes,   
    'shapefile': shapefile, 
    'Stacked_Chart': True,               #Visualize Temporal Change over periods
    'Parallel_Categories_Diagram': False, #Quantifies Changes over multiple periods
    'Chord_Diagram': False                #Quantifies Change between two periods
}
Clustering_viz(param)

To see your visualization, Click the URL below (or locate files):
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ\QUAL_Stacked_Chart\index.html
Advanced options are available in
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ/QUAL_Stacked_Chart/data/CONFIG_Stacked_Chart.js

In [22]:
input_attributes2 = pd.read_csv("attributes/Categorical_data_zipcode.csv")
input_attributes2

     zipcode  Neighborhood Type
0      60004                  3
1      60005                  1
2      60007                  3
3      60008                  1
4      60010                  3
..       ...                ...
183    60714                  1
184    60803                  1
185    60804                  4
186    60805                  3
187    60827                  2

[188 rows x 2 columns]

In [23]:
shapefile2 = gpd.read_file('shp/zipcode_Cook_County.shp')
shapefile2 = shapefile2.rename(columns={'GEOID10': 'zipcode'})
shapefile2

    zipcode                                           geometry
0     60004  POLYGON ((-87.98511 42.14212, -87.98511 42.141...
1     60005  MULTIPOLYGON (((-87.95428 42.02977, -87.95441 ...
2     60007  POLYGON ((-88.01775 41.99247, -88.01816 41.992...
3     60008  MULTIPOLYGON (((-88.06230 42.07726, -88.06229 ...
4     60010  POLYGON ((-88.05268 42.15381, -88.05282 42.153...
..      ...                                                ...
184   60714  MULTIPOLYGON (((-87.84537 42.05445, -87.84537 ...
185   60803  POLYGON ((-87.74341 41.69079, -87.74323 41.690...
186   60804  POLYGON ((-87.77800 41.82887, -87.77800 41.829...
187   60805  POLYGON ((-87.70254 41.70617, -87.70279 41.706...
188   60827  POLYGON ((-87.65056 41.65577, -87.65071 41.655...

[189 rows x 2 columns]

In [24]:
param = {
    'title': "Neighborhood, Cook County (zipcode level)",
    'subject': "NEIGHBORHOOD",
    'filename_suffix': "Cook_2018_from_ACS_zipcode_from_file", 
    'layers': ["Neighborhood Type"],  #from column headers in your csv file
    'inputCSV': input_attributes2,   
    'shapefile': shapefile2, 
    'Stacked_Chart': True,               #Visualize Temporal Change over periods
    'Parallel_Categories_Diagram': False, #Quantifies Changes over multiple periods
    'Chord_Diagram': False                #Quantifies Change between two periods
}
Clustering_viz(param)

To see your visualization, Click the URL below (or locate files):
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ\QUAL_Cook_2018_from_ACS_zipcode_from_file\index.html
Advanced options are available in
F:\Github\MapLinksPlot\PYTHON_Categorical_Data_VIZ/QUAL_Cook_2018_from_ACS_zipcode_from_file/data/CONFIG_Cook_2018_from_ACS_zipcode_from_file.js