In [1]:
import json, math, copy
from geosnap.data import store_ltdb
from geosnap.data import Community
from geosnap.data import store_census
from geosnap.data import data_store
import pandas as pd
import shapely.wkt
import shapely.geometry
from datetime import datetime
from datetime import timedelta
from pathlib import Path
from INCS import linc
import urllib.parse
import webbrowser
import os
import pprint

In [2]:
param = {
		'title': "Neighborhood Analysis: Kmeans, All metros",
		'filename_suffix': "All",
		'allMetros': True,
		'years': [1980, 1990, 2000, 2010],
		'method': "kmeans",
		'nClusters': 8,
		'variables': [
					  "p_nonhisp_white_persons", 
					  "p_nonhisp_black_persons", 
					  "p_hispanic_persons", 
					  "p_native_persons", 
					  "p_asian_persons",
					 ],
	}

In [3]:
metros = data_store.msas()
metros

,geoid,name,type,geometry
0,10100,"Aberdeen, SD",Micro Area,"POLYGON ((-98.722481 45.243764, -98.72542 45.2..."
1,10140,"Aberdeen, WA",Micro Area,"POLYGON ((-124.305419 47.244644, -124.306367 4..."
2,10180,"Abilene, TX",Metro Area,"POLYGON ((-100.146543 32.522793, -100.146425 3..."
3,10220,"Ada, OK",Micro Area,"POLYGON ((-96.932515 34.680425, -96.9325219999..."
4,10260,"Adjuntas, PR",Micro Area,"POLYGON ((-66.829792 18.219989, -66.829769 18...."
...,...,...,...,...
940,49660,"Youngstown-Warren-Boardman, OH-PA",Metro Area,"POLYGON ((-81.00229 41.134189, -81.00231699999..."
941,49700,"Yuba City, CA",Metro Area,"POLYGON ((-121.62376 39.295621, -121.62339 39...."
942,49740,"Yuma, AZ",Metro Area,"POLYGON ((-114.763998 32.643364, -114.76331 32..."
943,49780,"Zanesville, OH",Micro Area,"POLYGON ((-82.19478599999999 40.020694, -82.19..."
944,49820,"Zapata, TX",Micro Area,"POLYGON ((-99.385401 26.981377, -99.3866499999..."

In [6]:
geoid       = metros.columns[0]
method      = param['method']
nClusters   = param['nClusters']
years       = param['years']
variables   = param['variables']
seqClusters = 5
distType    = 'tran'

In [7]:
metroid = '10220'

In [10]:
community = Community.from_ltdb(years=years, msa_fips=metroid)
community.gdf

,geoid,n_asian_under_15,n_black_under_15,n_hispanic_under_15,n_native_under_15,n_white_under_15,n_persons_under_18,n_asian_over_60,n_black_over_60,n_hispanic_over_60,...,year,n_total_housing_units_sample,p_nonhisp_white_persons,p_white_over_60,p_black_over_60,p_hispanic_over_60,p_native_over_60,p_asian_over_60,p_disabled,geometry
0,40123089598,0.000000,0.000000,0.000000,0.000000,0.004806,0.006100,0.000000,0.000000,0.000000,...,1980,0.008861,91.046025,24.016735,0.000000,0.000000e+00,0.000000,0.000000e+00,12.970711,"POLYGON ((-96.93259399999999 34.765889, -96.93..."
1,40123088600,0.999988,20.124397,21.099788,405.327499,840.685694,1432.110833,0.008309,0.033235,2.016594,...,1990,1859.142227,77.625839,14.229610,0.000694,4.210412e-02,1.988006,1.734795e-04,12.528625,"POLYGON ((-96.71149199999999 34.916282, -96.70..."
2,40123088700,0.000001,18.000003,17.003907,134.064549,381.258150,600.359889,0.000000,12.000000,0.000001,...,1990,990.717636,78.999848,19.694111,0.523678,4.578255e-08,2.794146,0.000000e+00,14.106595,"POLYGON ((-96.642054 34.739834, -96.638076 34...."
3,40123088800,0.023217,73.023217,30.348261,293.925390,1135.912169,1709.903907,2.000000,82.069652,2.046435,...,1990,2748.026686,80.275844,15.438666,1.244209,3.102476e-02,1.630610,3.032080e-02,10.462284,"POLYGON ((-96.704432 34.821056, -96.7029419999..."
4,40123088900,8.000000,30.000000,17.000000,140.000000,429.000000,704.000000,4.000000,7.000000,7.000000,...,1990,1842.000000,80.988681,20.859321,0.161700,1.617002e-01,1.617002,9.240009e-02,11.619312,"POLYGON ((-96.67058899999999 34.789603, -96.66..."
5,40123089000,0.976783,0.976783,14.651740,123.074616,459.087860,669.096130,0.000000,2.930348,1.953565,...,1990,1094.973389,84.980695,17.220077,0.115830,7.722008e-02,0.926641,0.000000e+00,10.154441,"POLYGON ((-96.772059 34.743261, -96.770566 34...."
6,40123089100,2.000000,22.000000,13.000000,119.000000,300.000000,505.000000,2.000000,7.000000,6.000000,...,1990,1300.000000,80.328597,29.973357,0.310835,2.664298e-01,2.309059,8.880995e-02,25.843695,"POLYGON ((-96.705181 34.770697, -96.7042759999..."
7,40123089200,0.991819,36.697311,8.926373,85.296455,234.069336,384.825867,0.000000,4.959096,0.000000,...,1990,972.974670,76.769406,25.742009,0.285388,0.000000e+00,1.997717,0.000000e+00,24.086758,"POLYGON ((-96.68665399999999 34.781827, -96.68..."
8,40123089300,3.008181,22.302689,15.073627,132.703548,623.930668,893.174149,2.000000,2.040904,6.000000,...,1990,1746.025360,86.808024,23.593450,0.056405,1.658222e-01,1.168669,5.527408e-02,12.587353,"POLYGON ((-96.69635799999999 34.76048, -96.694..."
9,40123089598,0.000000,14.875392,11.900519,158.671372,797.324281,1086.899628,0.991691,3.966913,1.983412,...,1990,1565.891787,88.854792,16.973446,0.102253,5.112519e-02,0.664630,2.556220e-02,12.474467,"POLYGON ((-96.93259399999999 34.765889, -96.93..."
10,40123089600,0.000000,0.000000,10.996094,72.935555,406.742218,545.640671,0.000000,0.000000,0.000000,...,1990,974.283295,88.461793,21.269823,0.000000,0.000000e+00,1.621206,0.000000e+00,14.161179,"POLYGON ((-96.932515 34.680425, -96.8009199999..."
11,40123088600,0.000247,10.999911,31.000539,362.998814,651.007950,1363.008541,0.000000,2.999965,7.000041,...,2000,2009.025914,71.767074,14.551853,0.060715,1.416713e-01,1.254806,0.000000e+00,14.389855,"POLYGON ((-96.71149199999999 34.916282, -96.70..."
12,40123088700,0.000003,12.000001,21.000021,129.000126,333.000358,604.000598,0.000000,8.000000,1.000003,...,2000,1027.000907,75.129533,17.184800,0.345423,4.317799e-02,1.381693,0.000000e+00,15.673577,"POLYGON ((-96.642054 34.739834, -96.638076 34...."
13,40123088800,4.000000,36.000000,45.000000,314.000000,914.000000,1635.000000,8.000000,35.000000,7.000000,...,2000,3011.000000,75.916385,18.784042,0.515236,1.030473e-01,1.472104,1.177683e-01,9.966142,"POLYGON ((-96.704432 34.821056, -96.7029419999..."
14,40123088900,10.000000,27.000000,23.000000,141.000000,359.000000,708.000000,6.000000,10.000000,3.000000,...,2000,1840.000000,73.309179,16.159420,0.241546,7.246377e-02,2.125604,1.449275e-01,9.734300,"POLYGON ((-96.67058899999999 34.789603, -96.66..."
15,40123089000,1.000000,6.000000,15.000000,207.000000,387.000000,772.000000,0.000000,3.000000,4.000000,...,2000,1177.000000,74.063503,15.376382,0.107028,1.427042e-01,1.034606,0.000000e+00,17.231538,"POLYGON ((-96.772059 34.743261, -96.770566 34...."
16,40123089100,0.000000,24.000000,34.000000,125.000000,260.000000,570.000000,1.000000,4.000000,1.000000,...,2000,1237.000000,70.141343,18.992933,0.176678,4.416961e-02,1.104240,4.416961e-02,15.989399,"POLYGON ((-96.705181 34.770697, -96.7042759999..."
17,40123089200,1.000000,17.000000,48.000000,111.000000,199.000000,475.000000,3.000000,5.000000,2.000000,...,2000,899.000000,63.655352,16.187990,0.261097,1.044386e-01,1.566580,1.566580e-01,14.882507,"POLYGON ((-96.68665399999999 34.781827, -96.68..."
18,40123089300,2.000000,23.000000,26.000000,143.000000,494.000000,879.000000,2.000000,4.000000,4.000000,...,2000,1733.000000,76.088789,18.656926,0.112391,1.123911e-01,0.927227,5.619556e-02,9.328463,"POLYGON ((-96.69635799999999 34.76048, -96.694..."
19,40123089598,4.000000,4.000155,37.000231,187.000707,671.004784,1108.007184,0.000002,4.000111,3.000072,...,2000,1731.012820,80.825775,18.707733,0.093307,6.998022e-02,0.863076,4.991406e-08,16.188466,"POLYGON ((-96.93259399999999 34.765889, -96.93..."
20,40123089600,0.000000,0.000000,12.000000,81.000000,354.000000,560.000000,0.000000,0.000000,3.000000,...,2000,911.000000,82.729412,17.600000,0.000000,1.411765e-01,1.505882,0.000000e+00,15.623529,"POLYGON ((-96.932515 34.680425, -96.8009199999..."
21,40123088600,5.000000,18.000000,101.000000,243.000000,482.000000,1302.000000,NaN,NaN,NaN,...,2010,2119.000000,66.754767,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.71149199999999 34.916282, -96.70..."
22,40123088700,0.000000,0.000000,10.000000,31.000000,191.000000,368.000000,NaN,NaN,NaN,...,2010,1115.000000,75.645397,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.642054 34.739834, -96.638076 34...."
23,40123088800,0.000000,67.000000,40.000000,195.000000,905.000000,1692.000000,NaN,NaN,NaN,...,2010,3209.000000,72.716117,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.704432 34.821056, -96.7029419999..."
24,40123088900,4.000000,10.000000,112.000000,67.000000,321.000000,805.000000,NaN,NaN,NaN,...,2010,1752.000000,60.224614,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.67058899999999 34.789603, -96.66..."
25,40123089000,0.000000,32.000000,14.000000,44.000000,391.000000,921.000000,NaN,NaN,NaN,...,2010,1512.000000,67.720609,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.772059 34.743261, -96.770566 34...."
26,40123089100,6.000000,0.000000,52.000000,51.000000,224.000000,513.000000,NaN,NaN,NaN,...,2010,1253.000000,66.148776,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.705181 34.770697, -96.7042759999..."
27,40123089200,0.000000,31.000000,47.000000,16.000000,88.000000,390.000000,NaN,NaN,NaN,...,2010,838.000000,54.450867,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.68665399999999 34.781827, -96.68..."
28,40123089300,0.000000,0.000000,78.000000,80.000000,379.000000,999.000000,NaN,NaN,NaN,...,2010,1824.000000,68.310572,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.69635799999999 34.76048, -96.694..."
29,40123089598,0.000000,13.000000,18.000000,97.000000,672.000000,1249.000000,NaN,NaN,NaN,...,2010,1998.000000,77.549039,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.93259399999999 34.765889, -96.93..."
30,40123089600,0.000000,0.000000,42.000000,30.000000,268.000000,535.000000,NaN,NaN,NaN,...,2010,938.000000,76.859100,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.932515 34.680425, -96.8009199999..."

In [11]:
clusters = community.cluster(columns=variables, method=method, n_clusters=nClusters)
clusters.gdf

,year,geoid,n_asian_under_15,n_black_under_15,n_hispanic_under_15,n_native_under_15,n_white_under_15,n_persons_under_18,n_asian_over_60,n_black_over_60,...,n_total_housing_units_sample,p_nonhisp_white_persons,p_white_over_60,p_black_over_60,p_hispanic_over_60,p_native_over_60,p_asian_over_60,p_disabled,geometry,kmeans
0,1980,40123089598,0.000000,0.000000,0.000000,0.000000,0.004806,0.006100,0.000000,0.000000,...,0.008861,91.046025,24.016735,0.000000,0.000000e+00,0.000000,0.000000e+00,12.970711,"POLYGON ((-96.93259399999999 34.765889, -96.93...",2
1,1990,40123088600,0.999988,20.124397,21.099788,405.327499,840.685694,1432.110833,0.008309,0.033235,...,1859.142227,77.625839,14.229610,0.000694,4.210412e-02,1.988006,1.734795e-04,12.528625,"POLYGON ((-96.71149199999999 34.916282, -96.70...",4
2,1990,40123088700,0.000001,18.000003,17.003907,134.064549,381.258150,600.359889,0.000000,12.000000,...,990.717636,78.999848,19.694111,0.523678,4.578255e-08,2.794146,0.000000e+00,14.106595,"POLYGON ((-96.642054 34.739834, -96.638076 34....",0
3,1990,40123088800,0.023217,73.023217,30.348261,293.925390,1135.912169,1709.903907,2.000000,82.069652,...,2748.026686,80.275844,15.438666,1.244209,3.102476e-02,1.630610,3.032080e-02,10.462284,"POLYGON ((-96.704432 34.821056, -96.7029419999...",2
4,1990,40123088900,8.000000,30.000000,17.000000,140.000000,429.000000,704.000000,4.000000,7.000000,...,1842.000000,80.988681,20.859321,0.161700,1.617002e-01,1.617002,9.240009e-02,11.619312,"POLYGON ((-96.67058899999999 34.789603, -96.66...",3
5,1990,40123089000,0.976783,0.976783,14.651740,123.074616,459.087860,669.096130,0.000000,2.930348,...,1094.973389,84.980695,17.220077,0.115830,7.722008e-02,0.926641,0.000000e+00,10.154441,"POLYGON ((-96.772059 34.743261, -96.770566 34....",7
6,1990,40123089100,2.000000,22.000000,13.000000,119.000000,300.000000,505.000000,2.000000,7.000000,...,1300.000000,80.328597,29.973357,0.310835,2.664298e-01,2.309059,8.880995e-02,25.843695,"POLYGON ((-96.705181 34.770697, -96.7042759999...",0
7,1990,40123089200,0.991819,36.697311,8.926373,85.296455,234.069336,384.825867,0.000000,4.959096,...,972.974670,76.769406,25.742009,0.285388,0.000000e+00,1.997717,0.000000e+00,24.086758,"POLYGON ((-96.68665399999999 34.781827, -96.68...",0
8,1990,40123089300,3.008181,22.302689,15.073627,132.703548,623.930668,893.174149,2.000000,2.040904,...,1746.025360,86.808024,23.593450,0.056405,1.658222e-01,1.168669,5.527408e-02,12.587353,"POLYGON ((-96.69635799999999 34.76048, -96.694...",6
9,1990,40123089598,0.000000,14.875392,11.900519,158.671372,797.324281,1086.899628,0.991691,3.966913,...,1565.891787,88.854792,16.973446,0.102253,5.112519e-02,0.664630,2.556220e-02,12.474467,"POLYGON ((-96.93259399999999 34.765889, -96.93...",6
10,1990,40123089600,0.000000,0.000000,10.996094,72.935555,406.742218,545.640671,0.000000,0.000000,...,974.283295,88.461793,21.269823,0.000000,0.000000e+00,1.621206,0.000000e+00,14.161179,"POLYGON ((-96.932515 34.680425, -96.8009199999...",1
11,2000,40123088600,0.000247,10.999911,31.000539,362.998814,651.007950,1363.008541,0.000000,2.999965,...,2009.025914,71.767074,14.551853,0.060715,1.416713e-01,1.254806,0.000000e+00,14.389855,"POLYGON ((-96.71149199999999 34.916282, -96.70...",4
12,2000,40123088700,0.000003,12.000001,21.000021,129.000126,333.000358,604.000598,0.000000,8.000000,...,1027.000907,75.129533,17.184800,0.345423,4.317799e-02,1.381693,0.000000e+00,15.673577,"POLYGON ((-96.642054 34.739834, -96.638076 34....",7
13,2000,40123088800,4.000000,36.000000,45.000000,314.000000,914.000000,1635.000000,8.000000,35.000000,...,3011.000000,75.916385,18.784042,0.515236,1.030473e-01,1.472104,1.177683e-01,9.966142,"POLYGON ((-96.704432 34.821056, -96.7029419999...",2
14,2000,40123088900,10.000000,27.000000,23.000000,141.000000,359.000000,708.000000,6.000000,10.000000,...,1840.000000,73.309179,16.159420,0.241546,7.246377e-02,2.125604,1.449275e-01,9.734300,"POLYGON ((-96.67058899999999 34.789603, -96.66...",3
15,2000,40123089000,1.000000,6.000000,15.000000,207.000000,387.000000,772.000000,0.000000,3.000000,...,1177.000000,74.063503,15.376382,0.107028,1.427042e-01,1.034606,0.000000e+00,17.231538,"POLYGON ((-96.772059 34.743261, -96.770566 34....",4
16,2000,40123089100,0.000000,24.000000,34.000000,125.000000,260.000000,570.000000,1.000000,4.000000,...,1237.000000,70.141343,18.992933,0.176678,4.416961e-02,1.104240,4.416961e-02,15.989399,"POLYGON ((-96.705181 34.770697, -96.7042759999...",0
17,2000,40123089200,1.000000,17.000000,48.000000,111.000000,199.000000,475.000000,3.000000,5.000000,...,899.000000,63.655352,16.187990,0.261097,1.044386e-01,1.566580,1.566580e-01,14.882507,"POLYGON ((-96.68665399999999 34.781827, -96.68...",5
18,2000,40123089300,2.000000,23.000000,26.000000,143.000000,494.000000,879.000000,2.000000,4.000000,...,1733.000000,76.088789,18.656926,0.112391,1.123911e-01,0.927227,5.619556e-02,9.328463,"POLYGON ((-96.69635799999999 34.76048, -96.694...",2
19,2000,40123089598,4.000000,4.000155,37.000231,187.000707,671.004784,1108.007184,0.000002,4.000111,...,1731.012820,80.825775,18.707733,0.093307,6.998022e-02,0.863076,4.991406e-08,16.188466,"POLYGON ((-96.93259399999999 34.765889, -96.93...",1
20,2000,40123089600,0.000000,0.000000,12.000000,81.000000,354.000000,560.000000,0.000000,0.000000,...,911.000000,82.729412,17.600000,0.000000,1.411765e-01,1.505882,0.000000e+00,15.623529,"POLYGON ((-96.932515 34.680425, -96.8009199999...",1
21,2010,40123088600,5.000000,18.000000,101.000000,243.000000,482.000000,1302.000000,NaN,NaN,...,2119.000000,66.754767,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.71149199999999 34.916282, -96.70...",4
22,2010,40123088700,0.000000,0.000000,10.000000,31.000000,191.000000,368.000000,NaN,NaN,...,1115.000000,75.645397,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.642054 34.739834, -96.638076 34....",6
23,2010,40123088800,0.000000,67.000000,40.000000,195.000000,905.000000,1692.000000,NaN,NaN,...,3209.000000,72.716117,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.704432 34.821056, -96.7029419999...",7
24,2010,40123088900,4.000000,10.000000,112.000000,67.000000,321.000000,805.000000,NaN,NaN,...,1752.000000,60.224614,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.67058899999999 34.789603, -96.66...",0
25,2010,40123089000,0.000000,32.000000,14.000000,44.000000,391.000000,921.000000,NaN,NaN,...,1512.000000,67.720609,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.772059 34.743261, -96.770566 34....",7
26,2010,40123089100,6.000000,0.000000,52.000000,51.000000,224.000000,513.000000,NaN,NaN,...,1253.000000,66.148776,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.705181 34.770697, -96.7042759999...",3
27,2010,40123089200,0.000000,31.000000,47.000000,16.000000,88.000000,390.000000,NaN,NaN,...,838.000000,54.450867,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.68665399999999 34.781827, -96.68...",5
28,2010,40123089300,0.000000,0.000000,78.000000,80.000000,379.000000,999.000000,NaN,NaN,...,1824.000000,68.310572,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.69635799999999 34.76048, -96.694...",7
29,2010,40123089598,0.000000,13.000000,18.000000,97.000000,672.000000,1249.000000,NaN,NaN,...,1998.000000,77.549039,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.93259399999999 34.765889, -96.93...",6
30,2010,40123089600,0.000000,0.000000,42.000000,30.000000,268.000000,535.000000,NaN,NaN,...,938.000000,76.859100,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((-96.932515 34.680425, -96.8009199999...",1

In [12]:
df_pivot = clusters.gdf.pivot(index='geoid', columns='year', values='kmeans')
df_pivot

year        1980 1990 2000 2010
geoid
40123088600  NaN    4    4    4
40123088700  NaN    0    7    6
40123088800  NaN    2    2    7
40123088900  NaN    3    3    0
40123089000  NaN    7    4    7
40123089100  NaN    0    0    3
40123089200  NaN    0    5    5
40123089300  NaN    6    2    7
40123089598    2    6    1    6
40123089600  NaN    1    1    1

In [19]:
yearList = []
for year in df_pivot.columns:
        aYearList = df_pivot[year].values.tolist()
        aYearList = list(map(float, aYearList)) 
        yearList.append(aYearList)
yearList

[[nan, nan, nan, nan, nan, nan, nan, nan, 2.0, nan],
 [4.0, 0.0, 2.0, 3.0, 7.0, 0.0, 0.0, 6.0, 6.0, 1.0],
 [4.0, 7.0, 2.0, 3.0, 4.0, 0.0, 5.0, 2.0, 1.0, 1.0],
 [4.0, 6.0, 7.0, 0.0, 7.0, 3.0, 5.0, 7.0, 6.0, 1.0]]

In [16]:
incs = linc(yearList)
incs

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
ave = sum(incs) / len(incs) if (len(incs) != 0) else -9999
ave

1.0