# Example Visualizations using CyberGIS-Vis

## Setup environment

In [3]:
!pip install jupyter_server

Defaulting to user installation because normal site-packages is not writeable
Collecting jupyter_server
  Downloading jupyter_server-1.13.5-py3-none-any.whl (397 kB)
     |████████████████████████████████| 397 kB 16.2 MB/s
Requirement already satisfied: tornado>=6.1.0 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (6.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (4.9.1)
Requirement already satisfied: packaging in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (21.3)
Requirement already satisfied: Send2Trash in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (1.8.0)
Collecting websocket-client
  Downloading websocket_client-1.2.3-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 3.8 MB/s
Requirement already satisfied: nbformat in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (5.1.3)
Requirement already satisfied: pyzmq>=17 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (22.3.0)
Requirement already satisfied: nbconvert in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (6.4.0)
Requirement already satisfied: terminado>=0.8.3 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (0.12.1)
Requirement already satisfied: traitlets>=5 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (5.1.1)
Requirement already satisfied: jupyter-client>=6.1.1 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (7.1.1)
Collecting anyio<4,>=3.1.0
  Downloading anyio-3.5.0-py3-none-any.whl (79 kB)
     |████████████████████████████████| 79 kB 13.5 MB/s
Requirement already satisfied: ipython-genutils in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (0.2.0)
Requirement already satisfied: jinja2 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (3.0.3)
Requirement already satisfied: argon2-cffi in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (21.3.0)
Requirement already satisfied: prometheus-client in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter_server) (0.12.0)
Requirement already satisfied: idna>=2.8 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from anyio<4,>=3.1.0->jupyter_server) (3.3)
Collecting sniffio>=1.1
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Requirement already satisfied: python-dateutil>=2.1 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter-client>=6.1.1->jupyter_server) (2.8.0)
Requirement already satisfied: nest-asyncio>=1.5 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter-client>=6.1.1->jupyter_server) (1.5.4)
Requirement already satisfied: entrypoints in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jupyter-client>=6.1.1->jupyter_server) (0.3)
Requirement already satisfied: ptyprocess in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from terminado>=0.8.3->jupyter_server) (0.7.0)
Requirement already satisfied: argon2-cffi-bindings in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from argon2-cffi->jupyter_server) (21.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jinja2->jupyter_server) (2.0.1)
Requirement already satisfied: testpath in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (0.5.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (1.5.0)
Requirement already satisfied: bleach in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (4.1.0)
Requirement already satisfied: pygments>=2.4.1 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (2.11.2)
Requirement already satisfied: mistune<2,>=0.8.1 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (0.8.4)
Requirement already satisfied: jupyterlab-pygments in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (0.1.2)
Requirement already satisfied: defusedxml in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (0.7.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbconvert->jupyter_server) (0.5.10)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from nbformat->jupyter_server) (3.2.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from packaging->jupyter_server) (3.0.7)
Requirement already satisfied: setuptools in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter_server) (59.8.0)
Requirement already satisfied: six>=1.11.0 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter_server) (1.16.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter_server) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->jupyter_server) (21.4.0)
Requirement already satisfied: cffi>=1.0.1 in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter_server) (1.15.0)
Requirement already satisfied: webencodings in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from bleach->nbconvert->jupyter_server) (0.5.1)
Requirement already satisfied: pycparser in /data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter_server) (2.21)
Installing collected packages: sniffio, websocket-client, anyio, jupyter-server
Successfully installed anyio-3.5.0 jupyter-server-1.13.5 sniffio-1.2.0 websocket-client-1.2.3

In [4]:
import pandas as pd
import geopandas as gpd
from Adaptive_Choropleth_Mapper import Adaptive_Choropleth_Mapper_viz, Adaptive_Choropleth_Mapper_log

## Visualizations for Spatiotemporal Data

### Set input data.

In [8]:
input_attributes_hiv = pd.read_csv("attributes/HIV_US_multiple_long.csv", dtype={'geoid':str})
input_attributes_hiv = input_attributes_hiv.rename(columns={'geoid': 'geoid'})
input_attributes_hiv

       geoid  period  Health Care Center (/100k pop)    HIV
0       1001    2012                        3.796153  15.50
1       1003    2012                        2.507915   7.50
2       1005    2012                        6.641990  14.71
3       1007    2012                        4.207311  17.70
4       1009    2012                        2.630077   6.92
...      ...     ...                             ...    ...
21954  56037    2018                        4.474590   9.15
21955  56039    2018                        0.265288  17.17
21956  56041    2018                        4.603247   0.00
21957  56043    2018                        7.180956   0.00
21958  56045    2018                        0.265288   0.00

[21959 rows x 4 columns]

In [6]:
shapefile_us = gpd.read_file("shp/US/counties.shp")
shapefile_us

,geoid,name,geometry
0,2013,"Aleutians East,AK","MULTIPOLYGON (((-162.63769 54.80112, -162.6440..."
1,2016,"Aleutians West,AK","MULTIPOLYGON (((177.44593 52.11133, 177.44302 ..."
2,28107,"Panola,MS","POLYGON ((-90.19854 34.51109, -90.19863 34.554..."
3,28101,"Newton,MS","POLYGON ((-88.91452 32.57695, -88.91559 32.558..."
4,28027,"Coahoma,MS","POLYGON ((-90.65700 33.98759, -90.66036 33.987..."
...,...,...,...
3216,27057,"Hubbard,MN","POLYGON ((-95.16917 47.15252, -95.16909 47.182..."
3217,27169,"Winona,MN","POLYGON ((-92.07949 44.10699, -92.07921 44.117..."
3218,2270,None,"POLYGON ((-160.85114 63.01269, -160.85156 62.9..."
3219,51515,None,"POLYGON ((-79.54339 37.32615, -79.54230 37.334..."
3220,46113,None,"POLYGON ((-102.79211 42.99998, -102.86790 42.9..."

### Adaptive Choropleth Mapper with Multiple Line Chart (MLC)

In [7]:
param_MLC_HIV = {
    'title': "Adaptive Choropleth Mapper with Multiple Line Charts",
    'Subject': "Temporal Patterns",
    'filename_suffix': "HIV_MLC",                                      # max 30 character      
    'inputCSV': input_attributes_hiv,   
    'shapefile': shapefile_us, 
    #'period': 2000,
    'periods': [2012, 2013, 2014, 2015, 2016, 2017, 2018],
    'variables': [         #enter variable names of the column you selected above.
            "HIV",
            "Health Care Center (/100k pop)"
        ],
    'NumOfMaps':2,
    'Initial_map_center':[37, -97],
    'Initial_map_zoom_level':4,    
    'Map_width':"650px",
    'Top10_Chart': True,     
    'Multiple_Line_Chart': True,
    'NumOfMLC':2,
    #'InitialVariableMLC': ['2012_HIV', '2013_HIV', '2014_HIV', '2015_HIV', '2016_HIV', '2017_HIV', '2018_HIV'],
    'DefaultRegion_MLC':"36061" 
}
Adaptive_Choropleth_Mapper_viz(param_MLC_HIV)
Adaptive_Choropleth_Mapper_log(param_MLC_HIV)

/data/cigi/cybergisx-easybuild/conda/python3-0.9.0/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:1990: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  result[:] = values

output directory :  ACM_HIV_MLC
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_HIV_MLC/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/suhan2/edit/Scenario_Analysis_Mapper_0.0.2/ACM_HIV_MLC/data/CONFIG_HIV_MLC.js

### Adaptive Choropleth Mapper with Comparison Line Chart (CLC)

In [5]:
param_CLC_hiv = {
    'title': "Adaptive Choropleth Mapper with Comparison Line Chart",
    'Subject': "Temporal Patterns",
    'filename_suffix': "HIV_CLC",                                      # max 30 character  
    'inputCSV': input_attributes_hiv,   
    'shapefile': shapefile_us, 
    'periods': [2012, 2013, 2014, 2015, 2016, 2017, 2018],
    'variables': [         #enter variable names of the column you selected above.
            "HIV",
            #"Health Care Center (/100k pop)"    
        ],
    'NumOfMaps':2,
    'Initial_map_center':[37, -97],
    'Initial_map_zoom_level':4,
    'Map_width':"650px",
    'Top10_Chart': True,     
    'Comparision_Chart': True,
    'NumOfCLC': 7, # set the number of x value of the Comparision_Chart
    #'InitialVariableCLC': ['2012_HIV', '2013_HIV', '2014_HIV', '2015_HIV', '2016_HIV', '2017_HIV', '2018_HIV'],
    #'InitialVariableCLC': ['2012_Health Care Center (/100k pop)', '2013_Health Care Center (/100k pop)', '2014_Health Care Center (/100k pop)', '2015_Health Care Center (/100k pop)', '2016_Health Care Center (/100k pop)', '2017_Health Care Center (/100k pop)', '2018_Health Care Center (/100k pop)'],
    'DefaultRegion_CLC': ["36061", "12086"] #New York, NY VS Miami-Dade, FL 
}
Adaptive_Choropleth_Mapper_viz(param_CLC_hiv)

output directory :  ACM_HIV_CLC
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_HIV_CLC/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/suhan2/edit/Scenario_Analysis_Mapper_0.0.2/ACM_HIV_CLC/data/CONFIG_HIV_CLC.js

### Adaptive Choropleth Mapper with Parallel Coordinate Plot (PCP)

In [6]:
param_PCP_hiv = {
    'title': "Adaptive Choropleth Mapper with Paralle Coordinate Plot",
    'filename_suffix': "HIV_PCP",                                      # max 30 character  
    #'inputCSV': "data_imputedx.csv",     
    'inputCSV': input_attributes_hiv,   
    'shapefile': shapefile_us, 
    'periods': [2012, 2013, 2014, 2015, 2016, 2017, 2018],
    'variables': [         #enter variable names of the column you selected above.
            "HIV",
            #"Health Care Center (/100k pop)"
        ],
    'NumOfMaps':2,
    'Initial_map_center':[37, -97],
    'Initial_map_zoom_level':4,    
    'Map_width':"650px",
    'Top10_Chart': True,    
    'Parallel_Coordinates_Plot': True,
    'NumOfPCP':7,
    #'InitialVariablePCP':['2012_HIV', '2013_HIV', '2014_HIV', '2015_HIV', '2016_HIV', '2017_HIV', '2018_HIV']
}
Adaptive_Choropleth_Mapper_viz(param_PCP_hiv)

output directory :  ACM_HIV_PCP
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_HIV_PCP/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/suhan2/edit/Scenario_Analysis_Mapper_0.0.2/ACM_HIV_PCP/data/CONFIG_HIV_PCP.js

## Visualizations for Exploring Relationship between data

### Set input data.

In [7]:
input_attributes = pd.read_csv("attributes/Los_Angeles_1980_1990_2000_2010.csv", dtype={'geoid':str})
input_attributes = input_attributes.rename(columns={'geoid': 'geoid'})
input_attributes

,geoid,n_asian_under_15,n_black_under_15,n_hispanic_under_15,n_native_under_15,n_white_under_15,n_persons_under_18,n_asian_over_60,n_black_over_60,n_hispanic_over_60,...,n_widowed_divorced,n_white_persons,year,n_total_housing_units_sample,p_white_over_60,p_black_over_60,p_hispanic_over_60,p_native_over_60,p_asian_over_60,p_disabled
0,06037101110,4.512923,0.0,17.805532,3.938551,118.074478,159.429260,0.328213,0.0,1.066691,...,72.042664,NaN,1980,216.045944,11.362683,0.0,0.181691,0.000000,0.055905,4.416492
1,06037101122,49.069336,0.0,193.180725,42.705280,1281.120850,1729.904922,3.555239,0.0,11.593910,...,781.720006,NaN,1980,2344.410583,11.367037,0.0,0.181974,0.000000,0.055802,4.420126
2,06037101210,5.341171,0.0,143.240494,2.913366,473.907501,649.680603,2.913366,0.0,30.590342,...,468.080780,NaN,1980,1035.216064,11.672832,0.0,1.294698,0.184957,0.123305,9.103987
3,06037101220,5.658829,0.0,151.759506,3.086634,502.092438,688.319336,3.086634,0.0,32.409657,...,495.919190,NaN,1980,1096.783936,11.672832,0.0,1.294698,0.184957,0.123305,9.103987
4,06037101300,60.132671,0.0,100.549713,13.800941,691.032837,959.165405,0.000000,0.0,12.815160,...,437.686981,NaN,1980,1358.406860,13.719433,0.0,0.334620,0.000000,0.000000,6.383527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9361,06037980031,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,281.000000,NaN,2010,25.000000,NaN,NaN,NaN,NaN,NaN,NaN
9362,06037980033,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,NaN,2010,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
9363,06037990100,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,NaN,2010,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
9364,06037990200,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,NaN,2010,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
9365,06037990300,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,NaN,2010,0.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
shapefile = gpd.read_file("shp/Los_Angeles_tract/Los_Angeles_2.shp")
shapefile = shapefile.rename(columns={'tractID': 'geoid', 'tract_key': 'name'})
shapefile

            geoid    name                                           geometry
0     06037101110  101110  POLYGON ((-118.29792 34.26322, -118.29696 34.2...
1     06037101122  101122  POLYGON ((-118.29697 34.27881, -118.29410 34.2...
2     06037101210  101210  POLYGON ((-118.29945 34.25598, -118.29792 34.2...
3     06037101220  101220  POLYGON ((-118.27610 34.24648, -118.27618 34.2...
4     06037101300  101300  POLYGON ((-118.26602 34.24036, -118.26657 34.2...
...           ...     ...                                                ...
2339  06037920108  920108  POLYGON ((-118.55944 34.44441, -118.55957 34.4...
2340  06037920200  920200  POLYGON ((-118.57207 34.47017, -118.57211 34.4...
2341  06037990100  990100  POLYGON ((-118.94518 34.04309, -118.93753 34.0...
2342  06037990200  990200  POLYGON ((-118.42545 33.76085, -118.42816 33.7...
2343  06037990300  990300  POLYGON ((-118.24463 33.71077, -118.24457 33.7...

[2344 rows x 3 columns]

### Adaptive Choropleth Mapper with Scatter Plot

In [9]:
param_Scatter = {
    'title': "Adaptive Choropleth Mapper with Scatter Plot",
    'filename_suffix': "LA_Scatter",
    'inputCSV': input_attributes,   
    'shapefile': shapefile,
    'period': 2010,
    'label': "short_name", #Pick variable,short_name,full_name from template/conversion_table_codebook.csv         
    'variables': [         #enter variable names of the column you selected above.
        "p_nonhisp_white_persons",
        "p_nonhisp_black_persons",
        "p_hispanic_persons",
        "p_asian_persons",
        "p_foreign_born_pop",
        "p_edu_college_greater",
        "p_unemployment_rate",
        "p_employed_manufacturing",
        "p_poverty_rate",
        "p_vacant_housing_units",
        "p_owner_occupied_units",
        "p_housing_units_multiunit_structures",
        "median_home_value",
        "p_structures_30_old",
        "p_household_recent_move",
        "p_persons_under_18",
        "p_persons_over_60",     
    ],
    'Map_width':"500px",
    'Map_height':"500px",
    'Scatter_Plot': True,        
} 
Adaptive_Choropleth_Mapper_viz(param_Scatter)

output directory :  ACM_LA_Scatter
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_LA_Scatter/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/suhan2/edit/Scenario_Analysis_Mapper_0.0.2/ACM_LA_Scatter/data/CONFIG_LA_Scatter.js

### Adaptive Choropleth Mapper with Correlogram

In [10]:
param_Correlogram = {
    'title': "Adaptive Choropleth Mapper with Correlogram",
    'filename_suffix': "LA_Correlogram",
    'inputCSV': input_attributes,   
    'shapefile': shapefile,
    'NumOfMaps':4,
    'period': 2010,
    'label': "short_name", #Pick variable,short_name,full_name from template/conversion_table_codebook.csv         
    'variables': [         #enter variable names of the column you selected above.
        "p_nonhisp_white_persons",
        "p_nonhisp_black_persons",
        "p_hispanic_persons",
        "p_asian_persons",
        "p_foreign_born_pop",
        "p_edu_college_greater",
        "p_unemployment_rate",
        "p_employed_manufacturing",
        "p_poverty_rate",
        "p_vacant_housing_units",
        "p_owner_occupied_units",
        "p_housing_units_multiunit_structures",
        "median_home_value",
        "p_structures_30_old",
        "p_household_recent_move",
        "p_persons_under_18",
        "p_persons_over_60",     
    ],
    'Map_width':"370px",
    'Map_height':"370px",
    'Correlogram': True,        
} 
Adaptive_Choropleth_Mapper_viz(param_Correlogram)

output directory :  ACM_LA_Correlogram
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_LA_Correlogram/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/suhan2/edit/Scenario_Analysis_Mapper_0.0.2/ACM_LA_Correlogram/data/CONFIG_LA_Correlogram.js

### Adaptive Choropleth Mapper with Stacked Chart

In [11]:
param_Stacked = {
    'title': "Adaptive Choropleth Mapper with Stacked Chart",
    'filename_suffix': "LA_ACM",
    'inputCSV': input_attributes,   
    'shapefile': shapefile,
    'periods': [1980, 1990, 2000, 2010],
    'NumOfMaps': 6,
    'label': "short_name", #Pick variable,short_name,full_name from template/conversion_table_codebook.csv         
    'variables': [         #enter variable names of the column you selected above.
        "p_nonhisp_white_persons",
        "p_nonhisp_black_persons",
        "p_hispanic_persons",
        "p_native_persons",
        "p_asian_persons",
        "p_hawaiian_persons",
        "p_asian_indian_persons",
        "p_chinese_persons",
        "p_filipino_persons",
        "p_japanese_persons",
        "p_korean_persons",            
        "p_other_language",
        "p_female_headed_families",
        "median_income_blackhh",
        "median_income_hispanichh",
        "median_income_asianhh",
        "per_capita_income",     
    ],
    'chart': "Stacked Chart",  #Comment out if you do not want to visualize this chart      
}  
Adaptive_Choropleth_Mapper_viz(param_Stacked)

output directory :  ACM_LA_ACM
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_LA_ACM/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/suhan2/edit/Scenario_Analysis_Mapper_0.0.2/ACM_LA_ACM/data/CONFIG_LA_ACM.js

### Adaptive Choropleth Mapper with Top 10 Bar Chart

In [12]:
param_bar = {
    'title': "Adaptive Choropleth Mapper with Stacked Chart",
    'filename_suffix': "LA_ACM",
    'inputCSV': input_attributes,   
    'shapefile': shapefile,
    'periods': [1980, 1990, 2000, 2010],
    'NumOfMaps': 3,
    'label': "short_name", #Pick variable,short_name,full_name from template/conversion_table_codebook.csv         
    'variables': [         #enter variable names of the column you selected above.           
        "p_other_language",
        "p_female_headed_families",
        "per_capita_income",     
    ],
    'Top10_Chart': True,  #Comment out if you do not want to visualize this chart      
}  
Adaptive_Choropleth_Mapper_viz(param_bar)

output directory :  ACM_LA_ACM
To see your visualization, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_LA_ACM/index.html
To access all visualizations that you have created, click the URL below (or locate the files):
https://cybergisx.cigi.illinois.edu/user/suhan2/view/Scenario_Analysis_Mapper_0.0.2/ACM_log.html
Advanced options are available in
https://cybergisx.cigi.illinois.edu/user/suhan2/edit/Scenario_Analysis_Mapper_0.0.2/ACM_LA_ACM/data/CONFIG_LA_ACM.js